### ISSUE TITLE
Issues launching HelloMaui on iOS

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui-samples#129]
### Description

The goal is to run the iOS sample on a physical iOS device. Unfortunately, it is not deploying on the connected device and is instead launching an iPad Pro 12.9" iOS 14.4 simulator, from which the app also fails to deploy.

### Reproduction

1. Connect physical iPhone device to MacBook
2. Open terminal and run `dotnet build HelloMaui -t:Run -f net6.0-ios`
3. Build runs, launches iPad Pro 12.9" iOS 14.4 simulator, attempts to launch app and fails

### Link

https://gist.github.com/rachelkang/35017258c7f04a0a64fce4f20cf08c4f

### Working from: 
MacBook Pro (16-inch, 2019)
macOS Big Sur version 11.2.3
### Connected physical device: 
iPhone 7
iOS 14.5 developer beta

**Comment by jonathanpeppers** [comment]
Hi @rachelkang, I think you need to change the `$(RuntimeIdentifier)` to `ios-arm64` to run on a device. You could either change the `.csproj` file or use the `-r` switch at the command-line:

    $ dotnet build HelloMaui -t:Run -f net6.0-ios -r ios-arm64

Let me know if that works, thanks.

The crash you get at startup, seems like a problem in Maui, to me:
```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
   at Microsoft.Maui.ViewExtensions.UpdateSemantics(UIView nativeView, IView view)
   at Microsoft.Maui.Handlers.ViewHandler.MapSemantics(IViewHandler handler, IView view)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass21_0[[Microsoft.Maui.IView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.IViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IViewHandler r, IFrameworkElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IViewHandler viewHandler, IFrameworkElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IViewHandler viewHandler, IFrameworkElement virtualView)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.HandlerExtensions.ToNative(IView view, IMauiContext context)
   at Microsoft.Maui.MauiUIApplicationDelegate`1[[HelloMaui.Startup, HelloMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].FinishedLaunching(UIApplication application, NSDictionary launchOptions)
--- End of stack trace from previous location ---
   at UIKit.UIApplication.Main(String[] args, IntPtr principal, IntPtr delegate)
   at UIKit.UIApplication.Main(String[] args, String principalClassName, String delegateClassName)
   at HelloMaui.Program.Main(String[] args) in /Users/rachelkang/net6-mobile-samples/HelloMaui/iOS/Program.cs:line 12
2021-04-09 09:34:47.389328-0400 HelloMaui[25843:192553] Unhandled managed exception: Object reference not set to an instance of an object (System.NullReferenceException)
   at Microsoft.Maui.ViewExtensions.UpdateSemantics(UIView nativeView, IView view)
   at Microsoft.Maui.Handlers.ViewHandler.MapSemantics(IViewHandler handler, IView view)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass21_0[[Microsoft.Maui.IView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.IViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IViewHandler r, IFrameworkElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IViewHandler viewHandler, IFrameworkElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IViewHandler viewHandler, IFrameworkElement virtualView)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.HandlerExtensions.ToNative(IView view, IMauiContext context)
   at Microsoft.Maui.MauiUIApplicationDelegate`1[[HelloMaui.Startup, HelloMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].FinishedLaunching(UIApplication application, NSDictionary launchOptions)
--- End of stack trace from previous location ---
   at UIKit.UIApplication.Main(String[] args, IntPtr principal, IntPtr delegate)
   at UIKit.UIApplication.Main(String[] args, String principalClassName, String delegateClassName)
   at HelloMaui.Program.Main(String[] args) in /Users/rachelkang/net6-mobile-samples/HelloMaui/iOS/Program.cs:line 12
```

**Comment by rachelkang** [comment]
@jonathanpeppers thanks for the suggestion! I tried both ways, and am now seeing this build error:

```
Build FAILED.

3   +[DVTExtendedPlatformInfo extendedPlatformInfoForPlatformIdentifier : error : ] (in DVTFoundation) [/Users/rachelkang/net6-mobile-samples/HelloMaui/HelloMaui.csproj]
/usr/local/share/dotnet/sdk/6.0.100-preview.3.21202.5/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(876,5): error MSB3073: The command "/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/14.4.100-preview.3.1326/tools/bin/mlaunch --launchdev bin/Debug/net6.0-ios/ios-arm64/HelloMaui.app/ --stdout /dev/ttys000 --stderr /dev/ttys000 --wait-for-exit" exited with code 134. [/Users/rachelkang/net6-mobile-samples/HelloMaui/HelloMaui.csproj]
    0 Warning(s)
    2 Error(s)
```

here's the full gist: https://gist.github.com/rachelkang/9aad005729e49e600e1ebffc60abea2a

and thanks for nothing the MAUI issue - I think we've since fixed that exception, but will definitely continue to keep an eye out for it

**Comment by jonathanpeppers** [comment]
Do you have an Xcode 12.4? I don't think 12.5 works yet.

I normally install them side-by-side and use `sudo xcode-select -s /Applications/Xcode12.4.app/` to switch between versions.
