### ISSUE TITLE
Maui-check fails on Android Emulator Setup

### ISSUE THREAD

**Issue by rlibbert** [dotnet/maui-samples#155]
running maui-check multiple times.  Windows 10 fresh build.  

Other reports here: https://github.com/Redth/dotnet-maui-check/issues/36

Output:

> Android Emulator Checkup...
  x Android Emulator - x86 - API30 - Google API's not created.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
☼ Recommendation: Create an Android Emulator
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

! Attempt to fix? [y/n] (y): y
» Attempting to fix: Android Emulator
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
        at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
Fix applied.  Checking again...

> Android Emulator Checkup...
  x Android Emulator - x86 - API30 - Google API's not created

**Comment by keithshep** [comment]
I'm seeing the same thing

**Comment by tgutzler** [comment]
same here

**Comment by jonathanpeppers** [comment]
If you're still seeing this, can you file a bug over here, thanks: https://github.com/Redth/dotnet-maui-check/issues
