### ISSUE TITLE
Monkey testing the bottom TabBar crashes the app

### ISSUE THREAD

**Issue by Legends** [dotnet/maui-samples#427]
**Repo**: https://github.com/dotnet/maui-samples/tree/main/8.0/Fundamentals/Shell

Deliberately clicking through the bottom TabBar in higher frequency crashes the app:

> 02-01 16:50:25.845 30444 30444 E AndroidRuntime: FATAL EXCEPTION: main
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime: Process: com.companyname.xaminals, PID: 30444
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime: android.runtime.JavaProxyThrowable: [System.NotSupportedException]: Unable to activate instance of type Microsoft.Maui.Controls.Platform.Compatibility.ShellSearchViewAdapter+CustomFilter from native handle 0x7fc7ac7734 (key_handle 0xc2a95d3).
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at Java.Interop.TypeManager.CreateInstance(Unknown Source:0)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at Java.Lang.Object.GetObject(Unknown Source:0)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at Java.Lang.Object._GetObject(Unknown Source:0)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at Java.Lang.Object.GetObject(Unknown Source:0)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at Java.Lang.Object.GetObject(Unknown Source:0)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at Android.Widget.Filter.n_PublishResults_Ljava_lang_CharSequence_Landroid_widget_Filter_FilterResults_(Unknown Source:0)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLL_V(Unknown Source:0)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at crc640ec207abc449b2ca.ShellSearchViewAdapter_CustomFilter.n_publishResults(Native Method)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at crc640ec207abc449b2ca.ShellSearchViewAdapter_CustomFilter.publishResults(ShellSearchViewAdapter_CustomFilter.java:47)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:284)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:236)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8056)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
> 02-01 16:50:25.845 30444 30444 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by Legends** [comment]
ok, doesn't crash when deployed to local Android. This happens only during live debugging (F5)
