### ISSUE TITLE
NativeEmbeddingDemo doesn't work. 

### ISSUE THREAD

**Issue by vallgrenerik** [dotnet/maui-samples#454]
Thank you @davidbritch for the examples at https://github.com/dotnet/maui-samples/tree/main/8.0/PlatformIntegration/NativeEmbeddingDemo

I'm currently migrating an Xamarin.iOS/Xamarin.Android application to net8.0-ios/android. 
I would like to see how I could implement some MAUI controls into this application and found this sample, which looks exactly what I want.
However the Android/iOS samples does not work. 
I get this error on Android: 
```
**System.ArgumentNullException:** 'Value cannot be null. (Parameter 'key')'

[ProfileInstaller] Installing profile for com.companyname.nativeembeddingdemo
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
[mono-rt]    at System.ThrowHelper.ThrowArgumentNullException(String name)
[mono-rt]    at System.ThrowHelper.ThrowKeyNullException()
[mono-rt]    at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Maui.Dispatching.IDispatcher, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.DispatcherVisualTreeContext, Microsoft.Maui.Controls.HotReload.Forms, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].GetOrAdd(IDispatcher key, Func`2 valueFactory)
[mono-rt]    at Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.VisualTreeContextBase.GetDispatcherContext(IDispatcher dispatcher)
[mono-rt]    at Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.FormsVisualTreeContext.<>c__DisplayClass9_0.<SubscribeToVisualTreeChanges>b__0()
[mono-rt]    at Microsoft.VisualStudio.DesignTools.MobileTap.DispatcherExtensions.<>c__DisplayClass3_0.<InvokeAsync>b__0()
[mono-rt]    at Microsoft.VisualStudio.DesignTools.MobileTap.DispatcherExtensions.<>c__DisplayClass4_0`1[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<InvokeAsync>b__1()
[mono-rt] --- End of stack trace from previous location ---
[mono-rt]    at Microsoft.VisualStudio.DesignTools.MobileTap.DispatcherExtensions.Invoke(IDispatcher dispatcher, Action callback)
[mono-rt]    at Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.FormsVisualTreeContext.SubscribeToVisualTreeChanges()
[mono-rt]    at Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.FormsVisualTreeContext.<.ctor>b__2_0(EmptyRequestInfo _)
[mono-rt]    at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.<>c__DisplayClass34_0`1[[Microsoft.VisualStudio.DesignTools.TapContract.TapOM.EmptyRequestInfo, Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].<RegisterMessageObserver>b__0(EmptyRequestInfo message)
[mono-rt]    at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.HandleMessage[EmptyRequestInfo,ResponseWithError](Func`2 callback, Message request)
[mono-rt]    at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.<>c__DisplayClass35_0`2[[Microsoft.VisualStudio.DesignTools.TapContract.TapOM.EmptyRequestInfo, Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[Microsoft.VisualStudio.DesignTools.TapContract.TapOM.ResponseWithError, Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].<RegisterMessageObserver>b__0(Message message)
[mono-rt]    at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.ProcessInboundMessage(Message message)
[mono-rt]    at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.<>c__DisplayClass48_0.<OnMessageReceived>b__0()
[mono-rt]    at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.WaitableActionsList.<>c__DisplayClass8_0.<AddAndSignal>b__0(Boolean isCancelled)
[mono-rt]    at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.ActionThread(Object list)
[mono-rt]    at System.Threading.Thread.StartCallback()
```

On iOS I get this error: 

```
[0:] Microsoft.Maui.FileImageSourceService: Warning: Unable to load image file 'dotnet_bot.png'.

System.InvalidOperationException: Unable to load image file.
   at Microsoft.Maui.FileImageSourceService.GetImageAsync(IFileImageSource imageSource, Single scale, CancellationToken cancellationToken)
[0:] Microsoft.Maui.FontRegistrar: Warning: Unable to load font 'OpenSansRegular'.

System.IO.FileNotFoundException: Native font with the name OpenSans-Regular.ttf was not found.
   at Microsoft.Maui.FontRegistrar.GetNativeFontStream(String filename, String alias)
   at Microsoft.Maui.FontRegistrar.LoadNativeAppFont(String font, String filename, String alias)
   at Microsoft.Maui.FontRegistrar.GetFont(String font)
Thread started: .NET Timer #5
Thread started: <Thread Pool> #6
Thread started: .NET TP Gate #7
Thread started: <Thread Pool> #8
Loaded assembly: /Users/rum327/Library/Developer/CoreSimulator/Devices/B92C26C9-D9EF-4FA7-BDDF-2D67B5EEA13F/data/Containers/Bundle/Application/E8BCAF27-2809-467F-88F1-7D6D92D75FBF/NativeEmbeddingDemo.iOS.app/System.Xml.XmlSerializer.dll [External]
**System.ArgumentNullException:** 'Value cannot be null. (Parameter 'key')'

2024-03-25 15:15:57.893749+0100 NativeEmbeddingDemo.iOS[70361:9535933] 
Unhandled Exception:
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.ThrowHelper.ThrowArgumentNullException(String name)
   at System.ThrowHelper.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Maui.Dispatching.IDispatcher, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.DispatcherVisualTreeContext, Microsoft.Maui.Controls.HotReload.Forms, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].GetOrAdd(IDispatcher key, Func`2 valueFactory)
   at Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.VisualTreeContextBase.GetDispatcherContext(IDispatcher dispatcher)
   at Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.FormsVisualTreeContext.<>c__DisplayClass9_0.<SubscribeToVisualTreeChanges>b__0()
   at M
icrosoft.VisualStudio.DesignTools.MobileTap.DispatcherExtensions.<>c__DisplayClass3_0.<InvokeAsync>b__0()
   at Microsoft.VisualStudio.DesignTools.MobileTap.DispatcherExtensions.<>c__DisplayClass4_0`1[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<InvokeAsync>b__1()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.DesignTools.MobileTap.DispatcherExtensions.Invoke(IDispatcher dispatcher, Action callback)
   at Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.FormsVisualTreeContext.SubscribeToVisualTreeChanges()
   at Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.FormsVisualTreeContext.<.ctor>b__2_0(EmptyRequestInfo _)
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.<>c__DisplayClass34_0`1[[Microsoft.VisualStudio.DesignTools.TapContract.TapOM.EmptyRequestInfo, Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neu
tral, PublicKeyToken=b03f5f7f11d50a3a]].<RegisterMessageObserver>b__0(EmptyRequestInfo message)
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.HandleMessage[EmptyRequestInfo,ResponseWithError](Func`2 callback, Message request)
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.<>c__DisplayClass35_0`2[[Microsoft.VisualStudio.DesignTools.TapContract.TapOM.EmptyRequestInfo, Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[Microsoft.VisualStudio.DesignTools.TapContract.TapOM.ResponseWithError, Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].<RegisterMessageObserver>b__0(Message message)
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.ProcessInboundMessage(Message message)
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.<>c__DisplayClass48_0.<OnMessageRece
ived>b__0()
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.WaitableActionsList.<>c__DisplayClass8_0.<AddAndSignal>b__0(Boolean isCancelled)
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.ActionThread(Object list)
   at System.Threading.Thread.StartCallback()
2024-03-25 15:15:57.897540+0100 NativeEmbeddingDemo.iOS[70361:9535933] Unhandled managed exception: Value cannot be null. (Parameter 'key') (System.ArgumentNullException)
   at System.ThrowHelper.ThrowArgumentNullException(String name)
   at System.ThrowHelper.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Maui.Dispatching.IDispatcher, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.DispatcherVisualTreeContext, Microsoft.Maui.Controls.HotReload.Forms, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].GetOrAdd(IDispatcher key, Func`2 valueFactory)
   at Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.VisualTreeContextBase.GetDispatcherContext(IDispatcher dispatcher)
   at Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.FormsVisualTreeContext.<>c__DisplayClass9_0.<SubscribeToVisualTreeChanges>b__0()

   at Microsoft.VisualStudio.DesignTools.MobileTap.DispatcherExtensions.<>c__DisplayClass3_0.<InvokeAsync>b__0()
   at Microsoft.VisualStudio.DesignTools.MobileTap.DispatcherExtensions.<>c__DisplayClass4_0`1[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<InvokeAsync>b__1()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.DesignTools.MobileTap.DispatcherExtensions.Invoke(IDispatcher dispatcher, Action callback)
   at Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.FormsVisualTreeContext.SubscribeToVisualTreeChanges()
   at Microsoft.VisualStudio.DesignTools.MobileTap.VisualTreeService.VisualTree.FormsVisualTreeContext.<.ctor>b__2_0(EmptyRequestInfo _)
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.<>c__DisplayClass34_0`1[[Microsoft.VisualStudio.DesignTools.TapContract.TapOM.EmptyRequestInfo, Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Cul
ture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].<RegisterMessageObserver>b__0(EmptyRequestInfo message)
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.HandleMessage[EmptyRequestInfo,ResponseWithError](Func`2 callback, Message request)
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.<>c__DisplayClass35_0`2[[Microsoft.VisualStudio.DesignTools.TapContract.TapOM.EmptyRequestInfo, Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[Microsoft.VisualStudio.DesignTools.TapContract.TapOM.ResponseWithError, Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].<RegisterMessageObserver>b__0(Message message)
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.ProcessInboundMessage(Message message)
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.<>c__DisplayClass48_0.<OnMes
sageReceived>b__0()
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.WaitableActionsList.<>c__DisplayClass8_0.<AddAndSignal>b__0(Boolean isCancelled)
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.ProtocolHandler.ActionThread(Object list)
   at System.Threading.Thread.StartCallback()

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x102dd40a0 - /Users/rum327/Library/Developer/CoreSimulator/Devices/B92C26C9-D9EF-4FA7-BDDF-2D67B5EEA13F/data/Containers/Bundle/Application/E8BCAF27-2809-467F-88F1-7D6D92D75FBF/NativeEmbeddingDemo.iOS.app/libmonosgen-2.0.dylib : mono_dump_native_crash_info
	0x102d8428c - /Users/rum327/Library/Developer/CoreSimulator/Devices/B92C26C9-D9EF-4FA7-BDDF-2D67B5EEA13F/data/Containers/Bundle/Application/E8BCAF27-2809-467F-88F1-7D6D92D75FBF/NativeEmbeddingDemo.iOS.app/libmonosgen-2.0.dylib : mono_handle_native_crash
	0x1030a6bc8 - /Users/rum327/Library/Developer/CoreSimulator/Devices/B92C26C9-D9EF-4FA7-BDDF-2D67B5EEA13F/data/Containers/Bundle/Application/E8BCAF27-2809-467F-88F1-7D6D92D75FBF/NativeEmbeddingDemo.iOS.app/libmonosgen-2.0.dylib : sigabrt_signal_handler.cold.1
	0x102dd3960 - /Users/rum327/Library/Developer/CoreSimulator/Devices/B92C26C9-D9EF-4FA7-BDDF-2D67B5EEA13F/data/Containers/Bundle/Application/E8BCAF27-2809-467F-88F1-7D6D92D75FBF/NativeEmbeddingDemo.iOS.app/libmonosgen-2.0.dylib : mono_runtime_setup_stat_profiler
	0x1011dfc60 - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x1012571d0 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x1801605cc - /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_c.dylib : abort
	0x102333098 - /Users/rum327/Library/Developer/CoreSimulator/Devices/B92C26C9-D9EF-4FA7-BDDF-2D67B5EEA13F/data/Containers/Bundle/Application/E8BCAF27-2809-467F-88F1-7D6D92D75FBF/NativeEmbeddingDemo.iOS.app/libxamarin-dotnet-debug.dylib : xamarin_find_protocol_wrapper_type
	0x102e610c4 - /Users/rum327/Library/Developer/CoreSimulator/Devices/B92C26C9-D9EF-4FA7-BDDF-2D67B5EEA13F/data/Containers/Bundle/Application/E8BCAF27-2809-467F-88F1-7D6D92D75FBF/NativeEmbeddingDemo.iOS.app/libmonosgen-2.0.dylib : mono_invoke_unhandled_exception_hook
	0x102ec38b4 - /Users/rum327/Library/Developer/CoreSimulator/Devices/B92C26C9-D9EF-4FA7-BDDF-2D67B5EEA13F/data/Containers/Bundle/Application/E8BCAF27-2809-467F-88F1-7D6D92D75FBF/NativeEmbeddingDemo.iOS.app/libmonosgen-2.0.dylib : start_wrapper
	0x1012574c0 - /usr/lib/system/libsystem_pthread.dylib : _pthread_start
	0x1012526f0 - /usr/lib/system/libsystem_pthread.dylib : thread_start

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1022749ec):0x1022749dc  c0 03 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..)..
....
0x1022749ec  e3 00 00 54 fd 7b bf a9 fd 03 00 91 ce e2 ff 97  
...T.{..........
0x1022749fc  bf 03 00 91 fd 7b c1 a8 c0 03 5f d6 c0 
03 5f d6  .....{...._..._.
0x102274a0c  70 0a 
80 d2 01 10 00 d4 e3 00 00 54 fd 7b bf a9  p..........
T.{..

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
```

Any ideas @davidbritch @jfversluis ? 😊

**Comment by davidbritch** [comment]
Hi @vallgrenerik 

Re: System.ArgumentNullException: Value cannot be null. (Parameter 'key')

This is actually a hot reload error. Hot reload doesn't work with native embedding apps. I added a note to the doc about this, but forgot to add it to the sample readme (I'll rectify this). So you have two options: (1) disable hot reload in VS, or (2) launch the app without debugging. This should get you over the first hurdle.

Native embedding seems to work on Android and Windows, but it's problematic on iOS and Mac Catalyst. The main issue on iOS/MacCat is that you can't interact with any MAUI controls you add to your native app, due to [this issue](https://github.com/dotnet/maui/issues/19340). This alone is a blocker on those platforms. On top of that, iOS/MacCat won't load a single project in the latest MAUI release.
